spring.application.name=medicalHistory-microservice
server.port=0
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

#Data Source Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/db_medicalH_pet_nova
spring.datasource.username=postgres
spring.datasource.password=0803861400Borys#

#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Hablitar Logs en Debug
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
