spring.application.name=pet-microservice
server.port=0
eureka.instance.instance-id=${spring.application.name}:${random.uuid}



spring.datasource.url=jdbc:postgresql://localhost:5432/db_pets_pet_nova
spring.datasource.username=postgres
spring.datasource.password=0803861400Borys#

#Configuration JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#Hailita Log de Securities en Debug
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG