#información base para comunicarse entre microservicios
spring.application.name=tenat-microservice


#Configuración Data Source
spring.datasource.url=jdbc:postgresql://localhost:5432/db_tenants_pet_nova
spring.datasource.username=postgres
spring.datasource.password=0803861400Borys#

#Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#JWT Configuration
jwt.secret=3uilvBItlYg08UumSc1gL4nSnEg3bjHa1qB27Vcp2tU=
