spring.application.name=office-microservice
server.port=0
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

#Configuración data source
spring.datasource.url=jdbc:postgresql://localhost:5432/db_offices_pet_nova
spring.datasource.username=postgres
spring.datasource.password=0803861400Borys#

#Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect