spring.application.name=api-gateway-petNova
server.port=8080

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

# Habilitar el descubrimiento automático de rutas mediante Eureka
spring.cloud.gateway.discovery.locator.enabled=true
# Convierte el serviceId a minúsculas para coincidir con lo que registra Eureka
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

discovery.locator.enabled: true

#Definir rutas
spring.cloud.gateway.routes[0].id=user-microservice
spring.cloud.gateway.routes[0].uri=lb://user-microservice
spring.cloud.gateway.routes[0].predicates[0]=Path=/apiPetNova/auth/**, /apiPetNova/users/**

spring.cloud.gateway.routes[1].id=office-microservice
spring.cloud.gateway.routes[1].uri=lb://office-microservice
spring.cloud.gateway.routes[1].predicates[0]=Path=/apiPetNova/offices/**

spring.cloud.gateway.routes[2].id=pet-microservice
spring.cloud.gateway.routes[2].uri=lb://pet-microservice
spring.cloud.gateway.routes[2].predicates[0]=Path=/apiPetNova/pets/**, /apiPetNova/vaccines/**

spring.cloud.gateway.routes[3].id=appointment-microservice
spring.cloud.gateway.routes[3].uri=lb://appointment-microservice
spring.cloud.gateway.routes[3].predicates[0]=Path=/apiPetNova/appointments/**

spring.cloud.gateway.routes[4].id=medicalHistory-microservice
spring.cloud.gateway.routes[4].uri=lb://medicalHistory-microservice
spring.cloud.gateway.routes[4].predicates[0]=Path=/apiPetNova/medicalHistories/**

spring.cloud.gateway.routes[5].id=tenant-microservice
spring.cloud.gateway.routes[5].uri=lb://tenant-microservice
spring.cloud.gateway.routes[5].predicates[0]=Path=/apiPetNova/tenants/**


# JWT Configuration
jwt.secret=3uilvBItlYg08UumSc1gL4nSnEg3bjHa1qB27Vcp2tU=
jwt.expiration=3600000